# -*- coding: utf-8 -*-

"""
testapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from testapi.api_helper import APIHelper


class UsersResponse1(object):

    """Implementation of the 'UsersResponse1' model.

    Attributes:
        id (int): The model property of type int.
        message (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "message": 'message'
    }

    _optionals = [
        'id',
        'message',
    ]

    def __init__(self,
                 id=APIHelper.SKIP,
                 message=APIHelper.SKIP):
        """Constructor for the UsersResponse1 class"""

        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id 
        if message is not APIHelper.SKIP:
            self.message = message 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get("id") if dictionary.get("id") else APIHelper.SKIP
        message = dictionary.get("message") if dictionary.get("message") else APIHelper.SKIP
        # Return an object of this model
        return cls(id,
                   message)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'id={(self.id if hasattr(self, "id") else None)!r}, '
                f'message={(self.message if hasattr(self, "message") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'id={(self.id if hasattr(self, "id") else None)!s}, '
                f'message={(self.message if hasattr(self, "message") else None)!s})')
